package:
  name: lua-cjson
  version: 2.1.0.12
  epoch: 0
  description: "Lua CJSON is a fast JSON encoding/parsing module for Lua"
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - wolfi-baselayout
      - busybox
      - build-base
      - ca-certificates-bundle
      - luajit
      - luajit-dev

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/openresty/lua-cjson/archive/${{package.version}}.tar.gz
      expected-sha256: 97daf9b1626c30abac3cfa8160c88e0e95d0aac33dc5eafbd27fe507fbd86499
      strip-components: 1

  - name: "Configure"
    runs: |
      export LUAJIT_LIB=/usr/lib
      export LUA_LIB_DIR="$LUAJIT_LIB/lua"
      export LUAJIT_INC=/usr/include/luajit-2.1

      ln -sf /usr/bin/luajit /usr/bin/lua
      ln -sf "$LUAJIT_INC" /usr/include/lua

       export LUA_INCLUDE_DIR=/usr/include/luajit-2.1
       ln -sf $LUA_INCLUDE_DIR /usr/include/lua5.1

       make all

       make DESTDIR="${{targets.destdir}}" install

update:
  enabled: true
  github:
    identifier: openresty/lua-cjson
    strip-prefix: v
