package:
  name: modsecurity
  version: 3.0.10
  epoch: 3
  description: "ModSecurity is an open source, cross platform web application firewall (WAF) engine"
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - build-base
      - ca-certificates-bundle
      - git
      - cmake
      - autoconf
      - automake
      - pkgconf
      - make
      - libtool
      - curl
      - curl-dev
      - libxml2
      - pcre
      - pcre-dev
      - linux-headers
      - luajit

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/SpiderLabs/ModSecurity
      expected-commit: ccc2d9b53632fb5088673bbaafedf0d8d4b5f1d8
      tag: v${{package.version}}

  - name: 'Configure MODSECURITY'
    runs: |
      git submodule init
      git submodule update

      sh build.sh

      # https://github.com/SpiderLabs/ModSecurity/issues/1909#issuecomment-465926762
      sed -i '115i LUA_CFLAGS="${LUA_CFLAGS} -DWITH_LUA_JIT_2_1"' build/lua.m4
      sed -i '117i AC_SUBST(LUA_CFLAGS)' build/lua.m4
      ./configure \
      --disable-doxygen-doc \
      --disable-doxygen-html \
      --disable-examples

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: modsecurity-static
    pipeline:
      - uses: split/static
    description: modsecurity static libraries

  - name: modsecurity-config
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/etc/modsecurity
          cp modsecurity.conf-recommended ${{targets.subpkgdir}}/etc/modsecurity/
          cp modsecurity.conf-recommended ${{targets.subpkgdir}}/etc/modsecurity/modsecurity.conf-concurrent
          cp unicode.mapping ${{targets.subpkgdir}}/etc/modsecurity/

          # Replace serial logging with concurrent
          sed -i 's|SecAuditLogType Serial|SecAuditLogType Concurrent|g' ${{targets.subpkgdir}}/etc/modsecurity/modsecurity.conf-concurrent

          # Concurrent logging implies the log is stored in several files
          echo "SecAuditLogStorageDir /var/log/audit/" >> ${{targets.subpkgdir}}/etc/modsecurity/modsecurity.conf-concurrent
    description: modsecurity configuration files

update:
  enabled: true
  github:
    identifier: SpiderLabs/ModSecurity
    strip-prefix: v
    use-tag: true
